version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:15"
      timezone: "Etc/UTC"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    reviewers:
      - "dl-alexandre"
    assignees:
      - "dl-alexandre"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
